/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "./go"
	"os"
)

func main() {
	log.Printf("Server started")
	// Open or create a log file
	logFile, err := os.OpenFile("server.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	if err != nil {
		log.Fatalf("Failed to open log file: %v", err)
	}
	defer logFile.Close()
	

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8082", router))
}


// logError is a helper function to log errors and send an HTTP error response
func logError(w http.ResponseWriter, message string, statusCode int) {
	log.Println(message) // Log the error message
	http.Error(w, message, statusCode) // Send the HTTP error response
}