/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateSpeechRequest struct {
	// One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd` 
	Model *AnyOfCreateSpeechRequestModel `json:"model"`
	// The text to generate audio for. The maximum length is 4096 characters.
	Input string `json:"input"`
	// The voice to use when generating the audio. Supported voices are `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer`. Previews of the voices are available in the [Text to speech guide](/docs/guides/text-to-speech/voice-options).
	Voice string `json:"voice"`
	// The format to audio in. Supported formats are `mp3`, `opus`, `aac`, `flac`, `wav`, and `pcm`.
	ResponseFormat string `json:"response_format,omitempty"`
	// The speed of the generated audio. Select a value from `0.25` to `4.0`. `1.0` is the default.
	Speed float64 `json:"speed,omitempty"`
}
