/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of the tool call.
type RunStepDetailsToolCallsObject struct {
	// Always `tool_calls`.
	Type_ string `json:"type"`
	// An array of tool calls the run step was involved in. These can be associated with one of three types of tools: `code_interpreter`, `retrieval`, or `function`. 
	ToolCalls []OneOfRunStepDetailsToolCallsObjectToolCallsItems `json:"tool_calls"`
}
