/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details on the action required to continue the run. Will be `null` if no action is required.
type RunObjectRequiredAction struct {
	// For now, this is always `submit_tool_outputs`.
	Type_ string `json:"type"`

	SubmitToolOutputs *RunObjectRequiredActionSubmitToolOutputs `json:"submit_tool_outputs"`
}
