/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A list of the categories along with their scores as predicted by model.
type CreateModerationResponseCategoryScores struct {
	// The score for the category 'hate'.
	Hate float64 `json:"hate"`
	// The score for the category 'hate/threatening'.
	Hatethreatening float64 `json:"hate/threatening"`
	// The score for the category 'harassment'.
	Harassment float64 `json:"harassment"`
	// The score for the category 'harassment/threatening'.
	Harassmentthreatening float64 `json:"harassment/threatening"`
	// The score for the category 'self-harm'.
	SelfHarm float64 `json:"self-harm"`
	// The score for the category 'self-harm/intent'.
	SelfHarmintent float64 `json:"self-harm/intent"`
	// The score for the category 'self-harm/instructions'.
	SelfHarminstructions float64 `json:"self-harm/instructions"`
	// The score for the category 'sexual'.
	Sexual float64 `json:"sexual"`
	// The score for the category 'sexual/minors'.
	Sexualminors float64 `json:"sexual/minors"`
	// The score for the category 'violence'.
	Violence float64 `json:"violence"`
	// The score for the category 'violence/graphic'.
	Violencegraphic float64 `json:"violence/graphic"`
}
