/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChatCompletionRequestMessageContentPartText struct {
	// The type of the content part.
	Type_ string `json:"type"`
	// The text content.
	Text string `json:"text"`
}
