/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateCompletionResponseLogprobs struct {

	TextOffset []int32 `json:"text_offset,omitempty"`

	TokenLogprobs []float64 `json:"token_logprobs,omitempty"`

	Tokens []string `json:"tokens,omitempty"`

	TopLogprobs []map[string]float64 `json:"top_logprobs,omitempty"`
}
