/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RunStepDeltaStepDetailsToolCallsCodeOutputImageObject struct {
	// The index of the output in the outputs array.
	Index int32 `json:"index"`
	// Always `image`.
	Type_ string `json:"type"`

	Image *RunStepDeltaStepDetailsToolCallsCodeOutputImageObjectImage `json:"image,omitempty"`
}
