/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a transcription response returned by model, based on the provided input.
type CreateTranscriptionResponseJson struct {
	// The transcribed text.
	Text string `json:"text"`
}
