/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateAssistantRequest struct {
	// ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them. 
	Model *AnyOfCreateAssistantRequestModel `json:"model"`
	// The name of the assistant. The maximum length is 256 characters. 
	Name string `json:"name,omitempty"`
	// The description of the assistant. The maximum length is 512 characters. 
	Description string `json:"description,omitempty"`
	// The system instructions that the assistant uses. The maximum length is 32768 characters. 
	Instructions string `json:"instructions,omitempty"`
	// A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `retrieval`, or `function`. 
	Tools []OneOfCreateAssistantRequestToolsItems `json:"tools,omitempty"`
	// A list of [file](/docs/api-reference/files) IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order. 
	FileIds []string `json:"file_ids,omitempty"`
	// Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
	Metadata *interface{} `json:"metadata,omitempty"`
}
