/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageDeltaContentTextAnnotationsFileCitationObjectFileCitation struct {
	// The ID of the specific File the citation is from.
	FileId string `json:"file_id,omitempty"`
	// The specific quote in the file.
	Quote string `json:"quote,omitempty"`
}
