/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RunStepDeltaStepDetailsToolCallsRetrievalObject struct {
	// The index of the tool call in the tool calls array.
	Index int32 `json:"index"`
	// The ID of the tool call object.
	Id string `json:"id,omitempty"`
	// The type of tool call. This is always going to be `retrieval` for this type of tool call.
	Type_ string `json:"type"`
	// For now, this is always going to be an empty object.
	Retrieval *interface{} `json:"retrieval,omitempty"`
}
