/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The hyperparameters used for the fine-tuning job.
type CreateFineTuningJobRequestHyperparameters struct {
	// Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. 
	BatchSize *OneOfCreateFineTuningJobRequestHyperparametersBatchSize `json:"batch_size,omitempty"`
	// Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. 
	LearningRateMultiplier *OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier `json:"learning_rate_multiplier,omitempty"`
	// The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. 
	NEpochs *OneOfCreateFineTuningJobRequestHyperparametersNEpochs `json:"n_epochs,omitempty"`
}
