/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of the message creation by the run step.
type RunStepDetailsMessageCreationObject struct {
	// Always `message_creation`.
	Type_ string `json:"type"`

	MessageCreation *RunStepDetailsMessageCreationObjectMessageCreation `json:"message_creation"`
}
