/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The delta containing the fields that have changed on the run step.
type RunStepDeltaObjectDelta struct {
	// The details of the run step.
	StepDetails *OneOfRunStepDeltaObjectDeltaStepDetails `json:"step_details,omitempty"`
}
