/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChatCompletionRequestToolMessage struct {
	// The role of the messages author, in this case `tool`.
	Role string `json:"role"`
	// The contents of the tool message.
	Content string `json:"content"`
	// Tool call that this message is responding to.
	ToolCallId string `json:"tool_call_id"`
}
