/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListPaginatedFineTuningJobsResponse struct {

	Data []FineTuningJob `json:"data"`

	HasMore bool `json:"has_more"`

	Object string `json:"object"`
}
