/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A chat completion message generated by the model.
type ChatCompletionResponseMessage struct {
	// The contents of the message.
	Content string `json:"content"`

	ToolCalls *[]ChatCompletionMessageToolCall `json:"tool_calls,omitempty"`
	// The role of the author of this message.
	Role string `json:"role"`

	FunctionCall *ChatCompletionRequestAssistantMessageFunctionCall `json:"function_call,omitempty"`
}
