/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageDeltaContentImageFileObjectImageFile struct {
	// The [File](/docs/api-reference/files) ID of the image in the message content.
	FileId string `json:"file_id,omitempty"`
}
