/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a run step delta i.e. any changed fields on a run step during streaming. 
type RunStepDeltaObject struct {
	// The identifier of the run step, which can be referenced in API endpoints.
	Id string `json:"id"`
	// The object type, which is always `thread.run.step.delta`.
	Object string `json:"object"`

	Delta *RunStepDeltaObjectDelta `json:"delta"`
}
