/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Fine-tuning job event object
type FineTuningJobEvent struct {

	Id string `json:"id"`

	CreatedAt int32 `json:"created_at"`

	Level string `json:"level"`

	Message string `json:"message"`

	Object string `json:"object"`
}
