/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an embedding vector returned by embedding endpoint. 
type Embedding struct {
	// The index of the embedding in the list of embeddings.
	Index int32 `json:"index"`
	// The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the [embedding guide](/docs/guides/embeddings). 
	Embedding []float64 `json:"embedding"`
	// The object type, which is always \"embedding\".
	Object string `json:"object"`
}
