/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageDeltaContentTextAnnotationsFilePathObjectFilePath struct {
	// The ID of the file that was generated.
	FileId string `json:"file_id,omitempty"`
}
