/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The function definition.
type RunToolCallObjectFunction struct {
	// The name of the function.
	Name string `json:"name"`
	// The arguments that the model expects you to pass to the function.
	Arguments string `json:"arguments"`
}
