/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The delta containing the fields that have changed on the Message.
type MessageDeltaObjectDelta struct {
	// The entity that produced the message. One of `user` or `assistant`.
	Role string `json:"role,omitempty"`
	// The content of the message in array of text and/or images.
	Content []OneOfMessageDeltaObjectDeltaContentItems `json:"content,omitempty"`
	// A list of [file](/docs/api-reference/files) IDs that the assistant should use. Useful for tools like retrieval and code_interpreter that can access files. A maximum of 10 files can be attached to a message.
	FileIds []string `json:"file_ids,omitempty"`
}
