/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an execution run on a [thread](/docs/api-reference/threads).
type RunObject struct {
	// The identifier, which can be referenced in API endpoints.
	Id string `json:"id"`
	// The object type, which is always `thread.run`.
	Object string `json:"object"`
	// The Unix timestamp (in seconds) for when the run was created.
	CreatedAt int32 `json:"created_at"`
	// The ID of the [thread](/docs/api-reference/threads) that was executed on as a part of this run.
	ThreadId string `json:"thread_id"`
	// The ID of the [assistant](/docs/api-reference/assistants) used for execution of this run.
	AssistantId string `json:"assistant_id"`
	// The status of the run, which can be either `queued`, `in_progress`, `requires_action`, `cancelling`, `cancelled`, `failed`, `completed`, or `expired`.
	Status string `json:"status"`

	RequiredAction *RunObjectRequiredAction `json:"required_action"`

	LastError *RunObjectLastError `json:"last_error"`
	// The Unix timestamp (in seconds) for when the run will expire.
	ExpiresAt int32 `json:"expires_at"`
	// The Unix timestamp (in seconds) for when the run was started.
	StartedAt int32 `json:"started_at"`
	// The Unix timestamp (in seconds) for when the run was cancelled.
	CancelledAt int32 `json:"cancelled_at"`
	// The Unix timestamp (in seconds) for when the run failed.
	FailedAt int32 `json:"failed_at"`
	// The Unix timestamp (in seconds) for when the run was completed.
	CompletedAt int32 `json:"completed_at"`
	// The model that the [assistant](/docs/api-reference/assistants) used for this run.
	Model string `json:"model"`
	// The instructions that the [assistant](/docs/api-reference/assistants) used for this run.
	Instructions string `json:"instructions"`
	// The list of tools that the [assistant](/docs/api-reference/assistants) used for this run.
	Tools []OneOfRunObjectToolsItems `json:"tools"`
	// The list of [File](/docs/api-reference/files) IDs the [assistant](/docs/api-reference/assistants) used for this run.
	FileIds []string `json:"file_ids"`
	// Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
	Metadata *interface{} `json:"metadata"`

	Usage *RunCompletionUsage `json:"usage"`
}
