/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of the Code Interpreter tool call the run step was involved in.
type RunStepDetailsToolCallsCodeObject struct {
	// The ID of the tool call.
	Id string `json:"id"`
	// The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
	Type_ string `json:"type"`

	CodeInterpreter *RunStepDetailsToolCallsCodeObjectCodeInterpreter `json:"code_interpreter"`
}
