/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ChatCompletionRole : The role of the author of a message
type ChatCompletionRole string

// List of ChatCompletionRole
const (
	SYSTEM ChatCompletionRole = "system"
	USER ChatCompletionRole = "user"
	ASSISTANT ChatCompletionRole = "assistant"
	TOOL ChatCompletionRole = "tool"
	FUNCTION ChatCompletionRole = "function"
)
