/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// On an incomplete message, details about why the message is incomplete.
type MessageObjectIncompleteDetails struct {
	// The reason the message is incomplete.
	Reason string `json:"reason"`
}
